### ISSUE TITLE
Can the app make use of raw sequences available?

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidatorapp#6]
Say I have both SwissProt FASTA file and BLAST databases on my computer running GV app. The SwissProt FASTA file can serve as raw sequences file, right?

A lot of times FASTA file and BLAST databases are placed side by side with the same name (different extensions). Is the app able to leverage this to pass raw_sequences option to GV? Should it?

**Comment by IsmailM** [comment]
I Interesting idea.. Yep that would work...

But I don't think it's worth the effort because extracting raw_sequences is extremely fast on GV when using the same local DB (5000 sequences would take a matter of 2-3 minutes if you extract from the same DB)...

This is because GV creates an index of the BLAST HITS accession numbers and then sends the BLAST DB a single request for all those sequences in fasta format (and `blastdbcmd` is quite fast)...
